In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,"sudh",34.565, True]

In [9]:
a1=np.array(l1)

In [10]:
a2 = np.array([[1,2,3],[4,5,6]])

In [11]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
a1

array(['4', '5', '6', 'sudh', '34.565', 'True'], dtype='<U32')

In [13]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
a1.ndim

1

In [16]:
a2.ndim

2

In [17]:
a3.ndim

3

In [18]:
a1.size

6

In [19]:
a2.size

6

In [20]:
a3.size

9

In [21]:
a1.shape

(6,)

In [22]:
a2.shape

(2, 3)

In [23]:
a3.shape

(1, 3, 3)

In [24]:
np.random.randint(2,5)

4

In [26]:
np.random.randint(2,50)

11

In [27]:
np.random.randint(2,50,(3,4))

array([[26, 35, 11, 37],
       [19, 32,  4,  5],
       [42, 35, 47, 37]])

In [28]:
np.random.randint(2,50,(2,3,4))

array([[[43, 48, 13, 25],
        [44,  2, 47,  9],
        [11, 47,  8, 39]],

       [[18, 31, 48, 15],
        [11,  2, 28, 27],
        [24, 20, 23, 19]]])

In [29]:
np.random.rand(2,3)

array([[0.78437465, 0.9444482 , 0.09259575],
       [0.34359999, 0.03304229, 0.63125583]])

In [31]:
a4 = np.random.randn(4,4)

In [32]:
a4.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [33]:
a4.reshape(2,8)

array([[ 1.56434446e+00, -1.66218683e+00,  1.33709386e+00,
         1.15714983e+00, -3.49585081e-01,  9.12715001e-01,
        -1.04015431e+00,  1.64382754e-01],
       [ 1.92691928e+00, -2.91701238e-02,  1.33371072e+00,
         2.42833375e-01, -9.75998443e-02, -3.02496026e+00,
        -1.83777442e+00,  4.31005287e-05]])

In [34]:
a4.reshape(8,2)

array([[ 1.56434446e+00, -1.66218683e+00],
       [ 1.33709386e+00,  1.15714983e+00],
       [-3.49585081e-01,  9.12715001e-01],
       [-1.04015431e+00,  1.64382754e-01],
       [ 1.92691928e+00, -2.91701238e-02],
       [ 1.33371072e+00,  2.42833375e-01],
       [-9.75998443e-02, -3.02496026e+00],
       [-1.83777442e+00,  4.31005287e-05]])

In [35]:
a4.reshape(16,1)

array([[ 1.56434446e+00],
       [-1.66218683e+00],
       [ 1.33709386e+00],
       [ 1.15714983e+00],
       [-3.49585081e-01],
       [ 9.12715001e-01],
       [-1.04015431e+00],
       [ 1.64382754e-01],
       [ 1.92691928e+00],
       [-2.91701238e-02],
       [ 1.33371072e+00],
       [ 2.42833375e-01],
       [-9.75998443e-02],
       [-3.02496026e+00],
       [-1.83777442e+00],
       [ 4.31005287e-05]])

In [36]:
a4.reshape(2,-1)

array([[ 1.56434446e+00, -1.66218683e+00,  1.33709386e+00,
         1.15714983e+00, -3.49585081e-01,  9.12715001e-01,
        -1.04015431e+00,  1.64382754e-01],
       [ 1.92691928e+00, -2.91701238e-02,  1.33371072e+00,
         2.42833375e-01, -9.75998443e-02, -3.02496026e+00,
        -1.83777442e+00,  4.31005287e-05]])

In [37]:
a4.reshape(2,-12232)

array([[ 1.56434446e+00, -1.66218683e+00,  1.33709386e+00,
         1.15714983e+00, -3.49585081e-01,  9.12715001e-01,
        -1.04015431e+00,  1.64382754e-01],
       [ 1.92691928e+00, -2.91701238e-02,  1.33371072e+00,
         2.42833375e-01, -9.75998443e-02, -3.02496026e+00,
        -1.83777442e+00,  4.31005287e-05]])

In [38]:
a4.reshape(2,2,4)

array([[[ 1.56434446e+00, -1.66218683e+00,  1.33709386e+00,
          1.15714983e+00],
        [-3.49585081e-01,  9.12715001e-01, -1.04015431e+00,
          1.64382754e-01]],

       [[ 1.92691928e+00, -2.91701238e-02,  1.33371072e+00,
          2.42833375e-01],
        [-9.75998443e-02, -3.02496026e+00, -1.83777442e+00,
          4.31005287e-05]]])

In [39]:
a1

array(['4', '5', '6', 'sudh', '34.565', 'True'], dtype='<U32')

In [40]:
a1[0]

'4'

In [41]:
a1[2:6]

array(['6', 'sudh', '34.565', 'True'], dtype='<U32')

In [42]:
a1[2:6:2]

array(['6', '34.565'], dtype='<U32')

In [43]:
a1[::-1]

array(['True', '34.565', 'sudh', '6', '5', '4'], dtype='<U32')

In [44]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a2[0]

array([1, 2, 3])

In [46]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [47]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [48]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [49]:
a2[[0,1],[1,2]]

array([2, 6])

In [51]:
a5 = np.random.randint(2,90,(6,5))

In [52]:
a5

array([[15, 34, 55, 31, 79],
       [19, 21,  7,  2, 24],
       [66, 40, 44, 67,  8],
       [88, 63, 23, 47, 52],
       [38,  9, 25, 20, 49],
       [61, 15, 77, 31, 52]])

In [53]:
a5[a5>40]

array([55, 79, 66, 44, 67, 88, 63, 47, 52, 49, 61, 77, 52])

In [54]:
a5

array([[15, 34, 55, 31, 79],
       [19, 21,  7,  2, 24],
       [66, 40, 44, 67,  8],
       [88, 63, 23, 47, 52],
       [38,  9, 25, 20, 49],
       [61, 15, 77, 31, 52]])

In [55]:
a5[0,1] = 100

In [56]:
a5

array([[ 15, 100,  55,  31,  79],
       [ 19,  21,   7,   2,  24],
       [ 66,  40,  44,  67,   8],
       [ 88,  63,  23,  47,  52],
       [ 38,   9,  25,  20,  49],
       [ 61,  15,  77,  31,  52]])

In [61]:
a6 = np.random.randint(0,3,(3,3))

In [58]:
a7 = np.random.randint(0,3,(3,3))

In [62]:
a6

array([[2, 0, 1],
       [2, 1, 2],
       [1, 1, 2]])

In [60]:
a7

array([[1, 0, 0],
       [1, 2, 0],
       [0, 0, 2]])

In [63]:
a6*a7 #element basis multiplication

array([[2, 0, 0],
       [2, 2, 0],
       [0, 0, 4]])

In [64]:
a6@a7 #correct way of matrix multiplication

array([[2, 0, 2],
       [3, 2, 4],
       [2, 2, 4]])

In [65]:
a6

array([[2, 0, 1],
       [2, 1, 2],
       [1, 1, 2]])

In [66]:
a6+100

array([[102, 100, 101],
       [102, 101, 102],
       [101, 101, 102]])

In [67]:
a6*2

array([[4, 0, 2],
       [4, 2, 4],
       [2, 2, 4]])

In [68]:
a6/0

C:\Users\HP\AppData\Local\Temp\ipykernel_8264\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\HP\AppData\Local\Temp\ipykernel_8264\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, nan, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [69]:
a6

array([[2, 0, 1],
       [2, 1, 2],
       [1, 1, 2]])

In [71]:
a6**3

array([[8, 0, 1],
       [8, 1, 8],
       [1, 1, 8]], dtype=int32)

In [74]:
a8 = np.zeros((4,4))

In [75]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
a9 = np.ones((4,5))

In [78]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [80]:
a9 + np.array([1,2,3,4,5]) #broadcasting coloumn wise

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [81]:
a9 + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [86]:
np.array([[1,2,3,4]]).T #transpose operation

array([[1],
       [2],
       [3],
       [4]])

In [85]:
a9 + np.array([[1,2,3,4]]).T #rowise broadcasting

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [88]:
a6.T 

array([[2, 2, 1],
       [0, 1, 1],
       [1, 2, 2]])

In [89]:
a5

array([[ 15, 100,  55,  31,  79],
       [ 19,  21,   7,   2,  24],
       [ 66,  40,  44,  67,   8],
       [ 88,  63,  23,  47,  52],
       [ 38,   9,  25,  20,  49],
       [ 61,  15,  77,  31,  52]])

In [90]:
np.sqrt(a5)

array([[ 3.87298335, 10.        ,  7.41619849,  5.56776436,  8.88819442],
       [ 4.35889894,  4.58257569,  2.64575131,  1.41421356,  4.89897949],
       [ 8.1240384 ,  6.32455532,  6.63324958,  8.18535277,  2.82842712],
       [ 9.38083152,  7.93725393,  4.79583152,  6.8556546 ,  7.21110255],
       [ 6.164414  ,  3.        ,  5.        ,  4.47213595,  7.        ],
       [ 7.81024968,  3.87298335,  8.77496439,  5.56776436,  7.21110255]])

In [91]:
np.exp(a5)

array([[3.26901737e+06, 2.68811714e+43, 7.69478527e+23, 2.90488497e+13,
        2.03828107e+34],
       [1.78482301e+08, 1.31881573e+09, 1.09663316e+03, 7.38905610e+00,
        2.64891221e+10],
       [4.60718663e+28, 2.35385267e+17, 1.28516001e+19, 1.25236317e+29,
        2.98095799e+03],
       [1.65163625e+38, 2.29378316e+27, 9.74480345e+09, 2.58131289e+20,
        3.83100800e+22],
       [3.18559318e+16, 8.10308393e+03, 7.20048993e+10, 4.85165195e+08,
        1.90734657e+21],
       [3.10429794e+26, 3.26901737e+06, 2.75851345e+33, 2.90488497e+13,
        3.83100800e+22]])

In [92]:
np.log10(a5)

array([[1.17609126, 2.        , 1.74036269, 1.49136169, 1.89762709],
       [1.2787536 , 1.32221929, 0.84509804, 0.30103   , 1.38021124],
       [1.81954394, 1.60205999, 1.64345268, 1.8260748 , 0.90308999],
       [1.94448267, 1.79934055, 1.36172784, 1.67209786, 1.71600334],
       [1.5797836 , 0.95424251, 1.39794001, 1.30103   , 1.69019608],
       [1.78532984, 1.17609126, 1.88649073, 1.49136169, 1.71600334]])

In [95]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [96]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [98]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [99]:
np.linspace(2,3,num=50, retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [100]:
np.logspace(2,4,num=4, base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [101]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=996f184455154c31722bf94a0fbeb5cd2e359daaad0b8633873797fab38a863f
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks
  Using cached cufflinks-0.17.3.tar.gz (81 kB)
  Using cached colorlover-0.3.0-py3-none-any.whl (8.9 kB)
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=672cb398c1120781d6bfb9a4ee39f1af251c077e399407f87efbf8c1e9b571bd
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [106]:
import cufflinks as cf #not an inbuild library
import numpy as np
import pandas as pd
import seaborn as sns

In [107]:
cf.go_offline()

In [111]:
df = pd.DataFrame(np.random.randn(100,3), columns = ['A','B','C'])

In [112]:
df

A         B         C
0  -1.339993  0.962309 -0.182920
1  -0.999498  0.081806  0.220761
2   0.648703 -3.258750  0.817761
3  -1.879618 -0.806475 -0.911334
4   1.165987 -0.065448  0.325569
..       ...       ...       ...
95  1.084932  0.074361 -0.983207
96  0.936178  0.665755 -2.821554
97  0.399783  0.323632  0.268464
98 -0.918428  1.394512  1.268747
99 -0.277711 -1.063053  0.796503

[100 rows x 3 columns]

In [113]:
df.iplot()

In [114]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [115]:
df1

0
0   74
1   65
2    4
3   66
4   75
..  ..
95  43
96  77
97  45
98  30
99  99

[100 rows x 1 columns]

In [116]:
df1.iplot()

In [118]:
df.iplot(x ='A',y='B', mode = 'markers')

In [120]:
df2 = sns.load_dataset('titanic')

In [121]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [122]:
df2.iplot(x='age', y = 'fare',mode ='markers')

In [125]:
df2.iplot(x='fare', y = 'pclass',mode ='markers')

In [126]:
df2.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [127]:
df2.iplot(kind = 'bar', x = 'sex', y = 'survived')